application: github-migrator
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(app/.*)?
  script: main.app
  secure: always

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  mime_type: image/x-icon

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
